### ISSUE TITLE
Crystal waters are built in same orientation

### ISSUE THREAD

**Issue by jchodera** [pandegroup/pdbfixer#100]
If you retain crystal waters, the protons are built in with the exact same reference orientation, which seems a bit silly.
![complex](https://cloud.githubusercontent.com/assets/3656088/8892315/882a20d4-3320-11e5-8097-ed18f488c68c.png)
A slightly more sophisticated algorithms to minimize the water protons (or do some orientational Monte Carlo) with everything else held fixed might be useful here.

**Comment by swails** [comment]
Have you tried turning off the external electric field?

\*\*ducks for cover\*\*

**Comment by peastman** [comment]
What PDB file are you starting from?  Are you sure it didn't include water hydrogens to begin with?  That isn't at all how addHydrogens() works.  It adds the hydrogens at random positions, then does a local energy minimization to fix them up.

**Comment by jchodera** [comment]
Whoops, you're totally right.  Those hydrogens had been added with LEaP in my toolchain.  Sorry about that!
