### ISSUE TITLE
simtk.openmm.app.Modeller error: AttributeError: 'float' object has no attribute 'createSystem'

### ISSUE THREAD

**Issue by jchodera** [pandegroup/pdbfixer#108]
I've run into this odd error when trying to minimally process an already-protonated PDB file with `simtk.openmm.app.Modeller` (using `openmm-dev` conda package, version `6.3.0.dev-a1a6112`):
```
mski1776:abl choderaj$ python process-pdbfixer-output.py
Traceback (most recent call last):
  File "process-pdbfixer-output.py", line 17, in <module>
    modeller.addHydrogens(pH)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/simtk/openmm/app/modeller.py", line 805, in addHydrogens
    system = forcefield.createSystem(newTopology, rigidWater=False)
AttributeError: 'float' object has no attribute 'createSystem'
```
Minimal test case can be found here:
* [`process-pdbfixer-output.py`](https://gist.github.com/jchodera/880e3e7fadba2907da5f#file-process-pdbfixer-output-py)
* [`3UE4-pdbfixer.pdb`](https://gist.github.com/jchodera/880e3e7fadba2907da5f#file-3ue4-pdbfixer-pdb)

**Comment by swails** [comment]
The callback for `addHydrogens` is:

```Python
    def addHydrogens(self, forcefield=None, pH=7.0, variants=None, platform=None):
```

So you're passing the `pH` as `forcefield`, which is why it's saying `float` has no `createSystem` attribute.  Change that to `addHydrogens(pH=pH)`.

**Comment by jchodera** [comment]
D'oh!  Good catch.

**Comment by jchodera** [comment]
If only we required named arguments for everything.  :)

**Comment by jchodera** [comment]
@swails : I was trying to reprocess PDBFixer-generated files to change their residue and hydrogen names to something `tleap` could read, but seem to have run into a dead end (which I recall is the same one I ran into earlier because `PDBFile` only outputs PDB-standard residue and atom names).

`tleap` complains:
```
> check complex
Checking 'complex'....
WARNING: The unperturbed charge of the unit: -7.999900 is not zero.
FATAL:  Atom .R<HIE 258>.A<HD1 18> does not have a type.
FATAL:  Atom .R<HIE 164>.A<HD1 18> does not have a type.
FATAL:  Atom .R<HIE 143>.A<HD1 18> does not have a type.
FATAL:  Atom .R<HIE 129>.A<HD1 18> does not have a type.
FATAL:  Atom .R<HIE 63>.A<HD1 18> does not have a type.
FATAL:  Atom .R<HIE 14>.A<HD1 18> does not have a type.
FATAL:  Atom .R<NASP 1>.A<H 15> does not have a type.
```
Any guess as to what the easiest automatable workflow for going from PDBFixer into `tleap` is for cases like this?  Just stripping the protons is one options, but I had hoped to use the `variant` selection capability of `simtk.openmm.app.Modeller` to allow me to select which sidechains should have alternative protonation states.

**Comment by swails** [comment]
The `pdb4amber` script released with AmberTools will just do the right thing if all the hydrogens are in place.  Unfortunately it's not really *importable* (yet -- I hope to rewrite it at some point to go through ParmEd instead of being a standalone program).

**Comment by jchodera** [comment]
Does `pdb4amber` get distributed with `ambermini`?  I don't see it getting installed on the path...

**Comment by jchodera** [comment]
Moved to https://github.com/choderalab/ambermini/issues/29
