### ISSUE TITLE
Add padding option for water box creation in GUI

### ISSUE THREAD

**Issue by jaimergp** [pandegroup/pdbfixer#114]
Instead of letting the user input each cube side manually, a JS enhanced 4th box could fill those three fields automatically. I have implemented this myself using my poor JS skills, and I am very surprised it's working (at least in Chromium).

![waterbox](https://cloud.githubusercontent.com/assets/2559438/12417336/b39b852e-bea7-11e5-8bfe-74df68833ccc.gif)

 Would you be interested in reviewing the JS code and potentially accepting a PR?

**Comment by jchodera** [comment]
Sounds useful!

**Comment by jaimergp** [comment]
Great! I have just forked the repo and committed my implementation. Please, review:

https://github.com/jaimergp/pdbfixer/commit/24e8991dc80bb966c5d630e87ca67169bd3dc75c

**Comment by jchodera** [comment]
Looks pretty clean to me.  Can you open a pull request?

**Comment by jaimergp** [comment]
Done! I'd suggest testing the PR from different browsers (IE, Edge, Safari...). I had no problems with Chromium 47 and the JS code is pretty standard, but you never know...

**Comment by ajasja** [comment]
@jchodera  Probably this can be closed? (the code is in https://github.com/pandegroup/pdbfixer/blob/8f609f84e0e0f453092a424f8623b1f872530c6e/pdbfixer/html/addHydrogens.html#L45)

**Comment by peastman** [comment]
Right, this was implemented a while ago.
