### ISSUE TITLE
CONNECT records lost in processing

### ISSUE THREAD

**Issue by spadavec** [pandegroup/pdbfixer#139]
After processing a PDB, the CONNECT records appear to have been deleted for a ligand in a PDB: 

Recipe to recreate (Using the web interface): 
1) Download 4djw
2) Select only items for Chain A to be kept (e.g. Protein and TLA/0KP)
3) Select None additional residues to be built in
4) Keep all heterogens 
5) Add hydrogrens for pH 7 and don't add Water 
6) Save and look at file. Residue 0KP (imatinib) will appear to not have any bonds, but the atoms are present 

[Screenshot of output in PyMOL 
](http://imgur.com/a/23bQJ)

**Comment by peastman** [comment]
I just sent a PR with the fix: #140.  Could you test it and verify it works for you?
