### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jchodera** [pandegroup/pdbfixer#149]
The PDBFixer license currently says `free` in the [conda recipe](https://github.com/jchodera/conda-recipes/blob/9d86577336b1e348f4223e2cf2e10bbdc1eb66b3/pdbfixer/meta.yaml#L36).

What about switching to the [same MIT license OpenMM is released under](https://github.com/pandegroup/openmm/blob/master/docs-source/licenses/Licenses.txt#L10-L33) for maximum compatibility?

**Comment by peastman** [comment]
That was a mistake by whoever created the conda recipe.  It's already MIT.

**Comment by jchodera** [comment]
Corrected in https://github.com/omnia-md/conda-recipes/pull/693
