### ISSUE TITLE
fixer.missingTerminals not being added

### ISSUE THREAD

**Issue by cxhernandez** [pandegroup/pdbfixer#150]
I'm trying to fix up a PDB to use with OpenMM, however after running the following and saving to a PDB,

```python
>>> fixer = PDBFixer('srckinase.pdb')
>>> fixer.findMissingResidues()
>>> fixer.findMissingAtoms()
>>> fixer.addMissingAtoms()
```

I get this traceback, when trying to load it into OpenMM :
```
Traceback (most recent call last):
  File "../../model.py", line 836, in __init__
    self.system = forcefield.createSystem(self.pdb.topology, nonbondedCutoff=1*nanometer, constraints=HBonds)
  File "/home/cxh/miniconda3/envs/deepchem/lib/python3.6/site-packages/simtk/openmm/app/forcefield.py", line 1077, in createSystem
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 1 (TRP).  The set of atoms is similar to NTRP, but it is missing 1 hydrogen atoms.
```

And when I go back to my `fixer` object, I find that `fixer.missingTerminals` never actually went away after adding missing atoms:

```python
>>> fixer.missingTerminals
{<Residue 261 (THR) of chain 0>: ['OXT']}
```

Is this a bug or am I missing a step to add terminal atoms?

**Comment by peastman** [comment]
I'm not sure what's happening.  Can you post the file?

**Comment by cxhernandez** [comment]
here's a  [gist](https://gist.github.com/cxhernandez/34e7cda4cb56fa6d9e8171964ed080e8)

**Comment by peastman** [comment]
When I execute your code with the file you provided, it works fine.  No exceptions.  What versions of PDBFixer and OpenMM do you have installed?

**Comment by cxhernandez** [comment]
```
openmm                    7.1.0rc1                 py36_0    omnia
pdbfixer                  1.4                      py36_0    omnia
```

**Comment by cxhernandez** [comment]
Nevermind. I tried it again now and it somehow works. Very odd....

**Comment by hjuinj** [comment]
I repeated the code above with the provided pdb, and I also see the missing terminal when I print `fixer.missingTerminals` after `fixer.addMissingAtoms()`. However, If I actually write out the pdb file after adding missing atoms I can see they are indeed added.
