### ISSUE TITLE
NameError: global name 'heterogens' is not defined

### ISSUE THREAD

**Issue by tevang** [pandegroup/pdbfixer#155]
Hello Peter,
For your information, pdbfixer fails to load this pdb file. Have a look at your earliest convenience.
[p38_protein.pdb.gz](https://github.com/pandegroup/pdbfixer/files/1251733/p38_protein.pdb.gz)

**Comment by peastman** [comment]
I just submitted a PR with the fix: #156.  Could you test it and verify it works for you?
