### ISSUE TITLE
Add option for specifying platform (or platform name) to use?

### ISSUE THREAD

**Issue by jchodera** [pandegroup/pdbfixer#160]
I suspect cases like https://github.com/pandegroup/pdbfixer/issues/92 may result from use of the GPU for minimization in cases where forces are very large. It would be useful if we could specify which platform to use, or somehow force use of the CPU.

Alternatively, implementation of https://github.com/pandegroup/openmm/issues/1961 would potentially obviate the need for this.

**Comment by peastman** [comment]
This is fixed by https://github.com/pandegroup/openmm/pull/1984.
