### ISSUE TITLE
Release 1.5

### ISSUE THREAD

**Issue by jchodera** [pandegroup/pdbfixer#171]
@peastman : I'm not sure how this happened, but we're apparently building and pushing a `pdbfixer 1.5` from [this git tag](https://github.com/omnia-md/conda-recipes/blob/master/pdbfixer/meta.yaml#L1-L7).

Can you cut and push an official release from that version?

**Comment by peastman** [comment]
Sorry about that.  I think I just forgot to create the github release.  I just created it.

**Comment by jchodera** [comment]
Thanks!
