### ISSUE TITLE
residue names based on protonation state?

### ISSUE THREAD

**Issue by nitroamos** [pandegroup/pdbfixer#172]
Is there any feature implemented whereby PDBFixer (or OpenMM) can name residues based on their protonation state? I'm interested in doing Amber and Gromacs calculations and I'm surveying approaches.

**Comment by peastman** [comment]
PDBFixer always produces standard PDB names for residues.  Your best bet is probably to process the output file after it's done to rename the residues.

Does Amber really not provide tools to do this automatically?  It's going to be an issue every time someone downloads a PDB file from RCSB and wants to simulate in with Amber.

**Comment by nitroamos** [comment]
I found the tool [pdb4amber](https://github.com/Amber-MD/pdb4amber) and it seems to work ok.
