### ISSUE TITLE
Adding side chains sometimes produces bad geometry

### ISSUE THREAD

**Issue by jlmaccal** [pandegroup/pdbfixer#2]
Even with the soft core minimization strategy, sometimes a geometry is produced that can't be minimized. See [this gist](https://gist.github.com/6473309) for an example. When pdbfixer is run on this file, residue 1 (Arg) is built with a geometry that badly clashes with neighboring residues. Upon simulation, minimization fails to resolve the clash and the system explodes immediately.

It might be worth trying multiple rotamers for each amino acid and select the one with the lowest energy. In the example pdb, it looks like a different rotamer could easily be accommodated.

It might also be nice to report some indication, perhaps based on the soft core energy, if the process has been successful.

**Comment by peastman** [comment]
This works much better in 1.1.  If you find situations that still have problems, open a new issue.
