### ISSUE TITLE
Switch travis-ci to create pdbfixer-dev conda package

### ISSUE THREAD

**Issue by jchodera** [pandegroup/pdbfixer#43]
We should follow @rmcgibbo's scheme here:

https://github.com/omnia-md/conda-recipes/issues/3#issuecomment-44909923

**Comment by peastman** [comment]
I think this is now happening?

**Comment by jchodera** [comment]
Nope, still using the old su-required:
https://github.com/pandegroup/pdbfixer/blob/master/.travis.yml

**Comment by jchodera** [comment]
Should I try to tackle this and fix the fact that `pdbfixer-dev` is not updating on binstar at the same time?

**Comment by peastman** [comment]
Sure.

**Comment by jchodera** [comment]
Addressed by #103
