### ISSUE TITLE
Addition of missing residues builds additional residues in overlapping/interlocking geometry

### ISSUE THREAD

**Issue by jchodera** [pandegroup/pdbfixer#46]
It appears that in some cases, asking pdbfixer to add missing residues causes the new residues to be built in very poor overlapping/interlocking geometries.

For example, this happens for `1AM0` (minimization after residue addition is disabled for illustrative purposes):
![output-nominimization](https://cloud.githubusercontent.com/assets/3656088/3347467/21bb1ea2-f8e3-11e3-8c2d-ced05bf4d73b.png)
 
This is referenced in #45

**Comment by peastman** [comment]
Is this still a problem?  Version 1.1 generally does a much better job when adding new residues.

**Comment by jchodera** [comment]
Did you give `1AM0` a try?  I think we took it out of our automated test set.

**Comment by jchodera** [comment]
Actually, I think that was a hopeless pathological case.  We had discussed coming up with a more reasonable loop remodeling dataset, so let's close this and focus on that in upcoming iterations.
