### ISSUE TITLE
Add option to retain residue numbering and chain ids; should be default

### ISSUE THREAD

**Issue by jchodera** [pandegroup/pdbfixer#54]
Currently, pdbfixer spits out PDB files renumbered to start from 1 and chain id A.  This is probably not what we want, since pdbfixer is just supposed to make it possible to simulate the system while retaining as much information as the user desires, rather than changing information like residue numbers and chain ids.

**Comment by jchodera** [comment]
Did @peastman already make changes to have PDBFixer retain residue numbering?  I'm noting issues with this...

**Comment by peastman** [comment]
No, I haven't done this.

**Comment by jchodera** [comment]
What would it take to do this?

**Comment by jchodera** [comment]
Any thoughts here?  We could really use this.

**Comment by peastman** [comment]
This is more challenging that it seems at first.  Somehow we need to guarantee that we're outputting valid, consistent identifiers.  Atom and residue ids need to be numeric, positive, in order, no more than 4 (for residues) or 5 (for atoms) digits, and unique.  Chain ids need to be single upper case letters, and again must be unique.  Usually the initial ids you load from the input file will satisfy that, but as soon as you start doing any editing of the topology it becomes a lot harder.  And even the input ids won't necessary be valid.  For example, if you load a PDBx file, the chain ids will be arbitrary strings.  (I know, I haven't implemented PDBx input yet, but it's one of the next things on my list.)

Right now the way it handles this is for the PDB writer to just ignore existing ids and generate new, guaranteed valid ones while writing the output file.

**Comment by jchodera** [comment]
> Right now the way it handles this is for the PDB writer to just ignore existing ids and generate new, guaranteed valid ones while writing the output file.

This comes at the price of a huge amount of information loss and potentially making the output unable to be analyzed in a useful way.

I agree that there are challenges, but it seems like adding a mode that does the following would be at least conceptually straightforward:
* Renumber all atoms consecutively
* For inserted residues, name the residues by their corresponding three-letter-code from the `SEQRES` section, number them sequentially from the previous residue (throwing an Exception if this causes something weird to happen), and use the same chain identifier as the previous residue

Our immediate use case is that we want to generate a bunch of mutations starting from the same structure, but the initial PDB file (from the RCSB) is missing a lot of residues.  If we use PDBFixer to model the mutations and build in the missing residues for each mutation, each instance ends up with the loops modeled in a different random way.  If we instead first build in the loops, we destroy the information about residue numbering and would have to figure out how things got re-mapped to make the mutations.  In either case, the resulting file becomes much harder to analyze because the canonical numbering is lost.
