### ISSUE TITLE
Add support for removing spans of residues

### ISSUE THREAD

**Issue by jchodera** [pandegroup/pdbfixer#55]
Often, we only want to simulate one domain of a protein (e.g. the kinase domain of a larger chain).  This may correspond to a specific residue range inside a PDB file, so we may need to delete the parts of the chain we don't care about.

For example, we could add a function like
```python
fixer.removeResiduesFromChain(retain_start, retain_end, chain_ids=None, chain_indices=None)
```
where `retain_start` and `retain_end` would be the first and last residues to retain, while the optional `chain_ids` or `chain_indices` would restrict the operation to only the specified chains (instead of applying this to all chains).

**Comment by peastman** [comment]
> The Modeller strategy won't work, since it doesn't keep track of residue indices in the PDB. It just numbers them sequentially.

With the latest changes, this is no longer an issue.

**Comment by peastman** [comment]
Given the changes in the latest version, can we mark this as closed?

**Comment by jchodera** [comment]
Thanks!
