### ISSUE TITLE
Which release should be included in Omnia?

### ISSUE THREAD

**Issue by jchodera** [pandegroup/pdbfixer#71]
Which release should be included in the first release of the Omnia suite?  Do you want to use [the 1.0 release from 13 Mar 2014](https://github.com/pandegroup/pdbfixer/releases/tag/v1.0), or something more recent?

**Comment by peastman** [comment]
I just created the 1.1 release.  That's the one to use.

**Comment by jchodera** [comment]
Thanks!

@kyleabeauchamp has just updated the corresponding [omnia reciple](https://github.com/omnia-md/conda-recipes/pull/67).

**Comment by mpharrigan** [comment]
The version string in `setup.py` needs to be changed for the 1.1 release
