### ISSUE TITLE
Have travis build pdbfixer-dev package and push to binstar

### ISSUE THREAD

**Issue by jchodera** [pandegroup/pdbfixer#75]
We have other projects build `*-dev` packages and push them to binstar so we can test development versions easily.  Would be great to do this here too.

**Comment by peastman** [comment]
Sounds like a good idea.  I don't know what's involved in that, but feel free to send a PR.

**Comment by jchodera** [comment]
I'm happy to do this, but on the condition that you clarify up front what behavior is and is not acceptable, since just ended in a lot of wasted effort on my behalf with openmm.

There are a few different schemes in use by omnia projects at the moment.

Yank, for example, first builds the conda package using `devtools/conda-recipe`:
https://github.com/choderalab/yank/blob/master/.travis.yml

This recipe runs the tests, failing if they don't pass:
https://github.com/choderalab/yank/blob/master/devtools/conda-recipe/meta.yaml#L43-L51

If all is well, the `devtools/ci/after_success.sh` script uploads the conda package to binstar:
https://github.com/choderalab/yank/blob/master/devtools/ci/after_sucess.sh

Would this behavior be acceptable?

**Comment by peastman** [comment]
The main requirement is that it not interfere with testing.  That means, for example:

* A problem with conda or binstar shouldn't prevent the tests from getting run, or cause them to fail inappropriately.

* It shouldn't cause travis to take much longer.  (This isn't likely to be an issue here, since "building" PDBFixer takes seconds at most.  Also, changes to PDBFixer are much less frequent than changes to OpenMM, so it's less important if it adds a minute or two to the process.)

**Comment by jchodera** [comment]
> A problem with conda or binstar shouldn't prevent the tests from getting run, or cause them to fail inappropriately.

In the build strategy I proposed above, an error in the conda recipe `meta.yaml` specified prerequisites or the `build.sh` script (which should just contain `python setup.py install`) would technically cause a failure and the tests not to be run.  So, formally, someone could mess up these files or add an unspecified prerequisite and the build will fail and the tests not to be run, but it seems very unlikely that this would happen once we got it working in the first place.

Now, does this mean that this strategy would be rejected here, or is it OK for this case?

**Comment by jchodera** [comment]
Working on this, assuming that this strategy will work for you.

**Comment by peastman** [comment]
Ok.  If someone makes a change to the repository and that breaks something, that's not a problem.  That just means there's something wrong with their changes.

**Comment by peastman** [comment]
Can this be closed now?

**Comment by jchodera** [comment]
This is working!
