### ISSUE TITLE
Convergence of refinement?

### ISSUE THREAD

**Issue by kyleabeauchamp** [pandegroup/pdbfixer#8]
So I ran a small peptide chunk (https://gist.github.com/kyleabeauchamp/7269220) extracted from a crystal structure.  I find that the geometry of the proton added to SER does not appear correct.  This could probably be fixed by downstream minimization / equilibration, but I imagine some applications might want a better structure from PDBFixer.  

Input:

![input](https://f.cloud.github.com/assets/1900459/1455740/119f6688-431f-11e3-8f34-2184ce130c58.png)

Output:

![output](https://f.cloud.github.com/assets/1900459/1455742/171111de-431f-11e3-8dbb-e92176739c6a.png)

Note the linearity of the SER hydroxyl.

**Comment by peastman** [comment]
I think we can call this "good enough".  If anyone finds other cases that should be dealt with, open a new issue for them.
