### ISSUE TITLE
Tests still failing on Python 3

### ISSUE THREAD

**Issue by peastman** [pandegroup/pdbfixer#82]
The OpenMM change fixed a lot of the failing test cases, but there are still a few failures on Python 3:

```
======================================================================
FAIL: Doctest: pdbfixer.pdbfixer.PDBFixer.__init__
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/travis/miniconda/envs/_test/lib/python3.3/doctest.py", line 2179, in runTest
raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for pdbfixer.pdbfixer.PDBFixer.__init__
File "/home/travis/miniconda/envs/_test/lib/python3.3/site-packages/pdbfixer-1.0-py3.3.egg/pdbfixer/pdbfixer.py", line 137, in __init__
----------------------------------------------------------------------
File "/home/travis/miniconda/envs/_test/lib/python3.3/site-packages/pdbfixer-1.0-py3.3.egg/pdbfixer/pdbfixer.py", line 171, in pdbfixer.pdbfixer.PDBFixer.__init__
Failed example:
outfile.write(file.read())
Exception raised:
Traceback (most recent call last):
File "/home/travis/miniconda/envs/_test/lib/python3.3/doctest.py", line 1313, in __run
compileflags, 1), test.globs)
File "<doctest pdbfixer.pdbfixer.PDBFixer.__init__[7]>", line 1, in <module>
outfile.write(file.read())
TypeError: must be str, not bytes
----------------------------------------------------------------------
File "/home/travis/miniconda/envs/_test/lib/python3.3/site-packages/pdbfixer-1.0-py3.3.egg/pdbfixer/pdbfixer.py", line 173, in pdbfixer.pdbfixer.PDBFixer.__init__
Failed example:
fixer = PDBFixer(filename=filename)
Exception raised:
Traceback (most recent call last):
File "/home/travis/miniconda/envs/_test/lib/python3.3/doctest.py", line 1313, in __run
compileflags, 1), test.globs)
File "<doctest pdbfixer.pdbfixer.PDBFixer.__init__[9]>", line 1, in <module>
fixer = PDBFixer(filename=filename)
File "/home/travis/miniconda/envs/_test/lib/python3.3/site-packages/pdbfixer-1.0-py3.3.egg/pdbfixer/pdbfixer.py", line 219, in __init__
raise Exception("Structure contains no atoms.")
Exception: Structure contains no atoms.
```

**Comment by peastman** [comment]
One of the failures is in this code:

    >>> file = urlopen(url)
    >>> outfile = open(filename, 'w')
    >>> outfile.write(file.read())

"file" is in binary mode.  "outfile" is in text mode.  Hence the error.  We could fix it as a doctest by opening outfile as 'wb', but I think that would make an already confusing example even more confusing.  When will users ever actually do what this code is doing: download a file from a URL, save it locally, then tell PDBFixer to open the local file?  If they want to read or write a local PDB file, they'll be doing it in text mode, not binary.  If they want to process a file from a URL, they'll use the "url=..." option to PDBFixer.  All this code dealing with urlopen() and binary streams does nothing but add confusion and get in the way of a clean, simple example.

This is one of my general objections to doctests.  They don't work very well as either tests _or_ examples, and trying to combine those two functions hurts both of them.  I suggest we turn off doctests, and clean up the examples so they're actually good examples without worrying about whether they can be executed as standalone tests.

**Comment by kyleabeauchamp** [comment]
Maybe we trim that docstring example?  Right it's way too comprehensive (https://github.com/pandegroup/pdbfixer/blob/master/pdbfixer/pdbfixer.py#L163).  

IMHO, the cleanest way is to have a *single* example in the docstring section and move the rest to separate nose tests.  Those code paths might be already tested in nose, not sure.

**Comment by peastman** [comment]
To be clear about what I'm proposing, here is the current examples/doctests:

```
        Start from a file object.

        >>> pdbid = '1VII'
        >>> url = 'http://www.rcsb.org/pdb/files/%s.pdb' % pdbid
        >>> file = urlopen(url)
        >>> fixer = PDBFixer(pdbfile=file)

        Start from a filename.
        
        >>> filename = 'test.pdb'
        >>> file = urlopen(url)
        >>> outfile = open(filename, 'w')
        >>> outfile.write(file.read())
        >>> outfile.close()
        >>> fixer = PDBFixer(filename=filename)
        
        Start from a URL.

        >>> fixer = PDBFixer(url=url)

        Start from a PDB code.
        
        >>> fixer = PDBFixer(pdbid=pdbid)
```

And I would like to replace all of that by this:

```
        Start from a file object.

        >>> fixer = PDBFixer(pdbfile=open('test.pdb'))

        Start from a filename.
        
        >>> fixer = PDBFixer(filename='test.pdb')
        
        Start from a URL.

        >>> fixer = PDBFixer(url='http://www.rcsb.org/pdb/files/1VII.pdb')

        Start from a PDB code.
        
        >>> fixer = PDBFixer(pdbid='1VII')
```

**Comment by kyleabeauchamp** [comment]
Looks good to me

**Comment by swails** [comment]
> And I would like to replace all of that by this:

+1

However, I still think it is worth trying to run the doctests.  doctests are easy to misuse, but can be a great tool to make sure that the examples are working Python code (which is *important* IMO).

If we can't somehow configure doctest externally to find a 'test.pdb' file included in the git repo, then turning it off is better than making the example complex just to get it to run.

**Comment by swails** [comment]
>```
 >>> fixer = PDBFixer(pdbfile=open('test.pdb'))
```

What about rewriting this as

```Python
>>> with open('test.pdb') as f:
...    fixer = PDBFixer(pdbfile=f)
```

It promotes safer behavior, IMO, and is more consistent with the rest of the examples (i.e., you don't generate the instance being passed to `PDBFixer` in the `PDBFixer` call itself).

But it's a small nit.

**Comment by peastman** [comment]
See #83.

**Comment by swails** [comment]
+1
