### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jchodera** [pandegroup/pdbfixer#88]
The last release was Nov 2014, and there have been 35 commits since then.  Perhaps it's time for a new release so we can update the `omnia` package and deliver the new features that have been added?

**Comment by peastman** [comment]
Some of the changes depend on changes in OpenMM.  So we can't release them until OpenMM 6.3 is out.

**Comment by jchodera** [comment]
Thanks for clarifying!

**Comment by jchodera** [comment]
Duplicate of #99
