### ISSUE TITLE
New release following OpenMM 6.3 conda package

### ISSUE THREAD

**Issue by jchodera** [pandegroup/pdbfixer#99]
We should get ready for a new release here once the OpenMM 6.3 conda package is out.

**Comment by jchodera** [comment]
@peastman: Now that OpenMM 6.3 is conda-packaged, should we get this ready for a release?

Let me know if I can help!

**Comment by peastman** [comment]
Yes, I think that would be a good idea.  Is everything in good shape for a release, or do you think there are any more changes that should be made first?

**Comment by jchodera** [comment]
How about we sweep the issues and see?

**Comment by peastman** [comment]
Can you confirm that #102 fixed your problem?  If so, are we now ready to release?

**Comment by jchodera** [comment]
Weird, pdbfixer-dev is not updating on binstar:
https://binstar.org/omnia/pdbfixer-dev/files

Let me create a PR to fix that, then test.

**Comment by jchodera** [comment]
Hopefully fixed by #103

**Comment by jchodera** [comment]
OK, now I will test the dev package.

**Comment by jchodera** [comment]
Wait, does `pdbfixer` and `pdbfixer-dev` need `openmm` 6.3 release package or a newer `openmm-dev`?

**Comment by jchodera** [comment]
Dev package works, but it would be great if we could address #105 (preserve residue numbers by default) before a release.

**Comment by peastman** [comment]
The issue described in #105 is fixed.  You're now running into a different problem, which is inherent in the PDB format - there's only so many characters for each field.  We can try to work around it in some way, but that will be an OpenMM change, not a PDBFixer change.

As a longer term solution, we should add support for writing PDBx/mmCIF files, since those don't have the restriction.  That could be a good feature for OpenMM 7.0.

**Comment by jchodera** [comment]
> As a longer term solution, we should add support for writing PDBx/mmCIF files, since those don't have the restriction. That could be a good feature for OpenMM 7.0.

Great idea!

**Comment by peastman** [comment]
Ok, I'm going to declare that we're ready to release.  All the open issues either require changes to OpenMM, or can wait till the next version.

**Comment by peastman** [comment]
I've created the 1.2 release on github.  Can you take care of the conda package?

**Comment by jchodera** [comment]
Done: https://github.com/omnia-md/conda-recipes/pull/288

**Comment by peastman** [comment]
Great!  I'll close this then.
